volumes:
  postgres_data:
  redis_data:

networks:
  technical_test:
    driver: bridge

services:
  http:
    image: service_test
    depends_on:
      - postgres
      - redis
    networks:
      - technical_test
    ports:
      - "8080:8080"
    entrypoint: "bin/entrypoint.sh"
    environment:
      DATABASE_URL: "postgres://admin:pwd@postgres:5432/technical_test?sslmode=disable"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: technical_test
      REDIS_HOST: redis
      REDIS_PORT: 6379

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=technical_test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pwd
    networks:
      - technical_test
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "postgres", "-d", "technical-test"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 30s
    #   timeout: 10s

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - technical_test
    # healthcheck:
    #   test: ["CMD", "redis-cli", "ping"]
    #   interval: 10s
    #   retries: 3